// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Contracts.Models;

public partial class DatabaseContext : DbContext
{
    public DatabaseContext(DbContextOptions<DatabaseContext> options)
        : base(options)
    {
    }

    public virtual DbSet<MyEntity> MyEntities { get; set; }

    public virtual DbSet<SomeDelta> SomeDeltas { get; set; }

    public virtual DbSet<Status> Status { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<MyEntity>(entity =>
        {
            entity.ToTable("MyEntity");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.SomeDelta).WithMany(p => p.MyEntities)
                .HasForeignKey(d => d.SomeDeltaId)
                .HasConstraintName("FK_MyEntity_SomeDelta_SomeDelta_Id");

            entity.HasOne(d => d.Status).WithMany(p => p.MyEntities)
                .HasForeignKey(d => d.StatusId)
                .HasConstraintName("FK_MyEntity_StatusId_Status_Id");
        });

        modelBuilder.Entity<SomeDelta>(entity =>
        {
            entity.ToTable("SomeDelta");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Name).HasMaxLength(50);
        });

        modelBuilder.Entity<Status>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Name).HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}