// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Contracts.Models;

public partial class MyEntity
{
    public int Id { get; set; }

    public int? SomeDeltaId { get; set; }

    public int? StatusId { get; set; }

    public virtual SomeDelta SomeDelta { get; set; }

    public virtual Status Status { get; set; }
}